---

- name: pull logstash image
  docker_image:
    name: docker.elastic.co/logstash/logstash:7.4.2
    source: pull

- name: Start a container logstash
  docker_container:
    name: logstash
    image: docker.elastic.co/logstash/logstash:7.4.2
    recreate: yes
    command: bin/logstash -e "input { tcp { port => 5959 codec => json}} output { elasticsearch { hosts => ["elastic:9600"]} }"
    env:
      xpack.monitoring.elasticsearch.hosts: elastic:9600
    # volumes:
    #  - ~/../files/logstash.yml:/usr/share/logstash/config/logstash.yml
    ports:
      - "5959:5959"
    network_mode: host
