---

#- name: common role - all
#  hosts: all
#  roles:
#    - roles/common

- hosts: elastic
  gather_facts: true
  # user: vagrant
  become: yes
  become_method: sudo
  roles:
    - roles/common
    - roles/java
    - roles/elasticsearch

- hosts: logstash
  gather_facts: true
  # user: vagrant
  become: yes
  become_method: sudo
  roles:
    - roles/common
    - roles/docker
    - roles/docker-logstash

- hosts: kibana
  gather_facts: true
  # user: vagrant
  become: yes
  become_method: sudo
  roles:
    - roles/common
    - roles/docker
    - roles/docker-kibana