---

- hosts: elastic
  gather_facts: true
  # user: vagrant
  become: yes
  become_method: sudo
  roles:
    - roles/common
    - roles/docker
    - roles/java
    - roles/elasticsearch
    - roles/docker-kibana
    - roles/docker-logstash