---
- name: add signing key
  rpm_key:
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: add repository
  template: src=elasticsearch.repo dest=/etc/yum.repos.d/
  # notify: restart nginx

- name: install elasticsearch
  yum: name=elasticsearch state=present

- name: daemon systemd
  service:
    name: elasticsearch
    state: started
    enabled: true
